WITH raw_reviews AS (

SELECT * from AIRBNB.RAW.RAW_REVIEWS
)
select
    LISTING_ID,
    DATE AS REVIEW_DATE,
    REVIEWER_NAME,
    COMMENTS AS REVIEW_TEXT,
    SENTIMENT AS REVIEW_SENTIMENT
FROM 
    raw_reviews